In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
filename = "/content/bostonHousing1978.csv"
df = pd.read_csv(filename)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   RM       506 non-null    float64
 1   LSTAT    506 non-null    float64
 2   PTRATIO  506 non-null    float64
 3   target   506 non-null    float64
dtypes: float64(4)
memory usage: 15.9 KB

In [ ]:
df.shape

(506, 4)

In [ ]:
df.dtypes

RM         float64
LSTAT      float64
PTRATIO    float64
target     float64
dtype: object

### algunos comandos asocidados a estas operaciones tienen () al final y otros no.
Son métodos: info(), head(), tail(), read_csv(), read_excel(). Un método es una función asociada con una clase específica. 

“shape” y “dtypes” son atributos donde los datos están asociados a una clase específica.

### Seleccionar columnas usando corchetes

con corchetes se pueden seleccionar una o mas columnas.
los corchetes simples devolveran una serie Pandas["x"]

mientas que los corchetes dobles devolveran un dataframe Pandas[["x"]]

In [ ]:
type(df[["RM"]].head())

pandas.core.frame.DataFrame

In [ ]:
type(df["RM"])

pandas.core.series.Series

In [ ]:
df[["RM","target"]].head() ## tambien se pueden seleccionar multiples columnas

      RM  target
0  6.575    24.0
1  6.421    21.6
2  7.185    34.7
3  6.998    33.4
4  7.147    36.2

In [ ]:
df[['RM', 'LSTAT', 'PTRATIO', 'target']].tail()

        RM  LSTAT  PTRATIO  target
501  6.593   9.67     21.0    22.4
502  6.120   9.08     21.0    20.6
503  6.976   5.64     21.0    23.9
504  6.794   6.48     21.0    22.0
505  6.030   7.88     21.0    11.9

In [ ]:
df["RM"].head()# single brackets generan una unidimensional panda.

0    6.575
1    6.421
2    7.185
3    6.998
4    7.147
Name: RM, dtype: float64

In [ ]:
df["RM","target"] # No se pueden seleccionar multiples columas con brackets simples

KeyError: ignored

In [ ]:
df["RM"][0:10] # 10 primeros resultados mediante SLICING

0    6.575
1    6.421
2    7.185
3    6.998
4    7.147
5    6.430
6    6.012
7    6.172
8    5.631
9    6.004
Name: RM, dtype: float64

In [ ]:
df["RM"].head(10) # 10 primeros resultados mediante funcion .head(10)

0    6.575
1    6.421
2    7.185
3    6.998
4    7.147
5    6.430
6    6.012
7    6.172
8    5.631
9    6.004
Name: RM, dtype: float64

In [ ]:
#tambien se puede utilizar el nombre de la columna aunque se recomienda el uso de brackets
df.RM.head()

0    6.575
1    6.421
2    7.185
3    6.998
4    7.147
Name: RM, dtype: float64

### Seleccioanr columnas usando loc

In [ ]:
# pandas dataframe
df.loc[:,["target"]].head()

   target
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2

In [ ]:
# pandas series
df.loc[:, 'RM'].head()

0    6.575
1    6.421
2    7.185
3    6.998
4    7.147
Name: RM, dtype: float64

In [ ]:
temp["count"]

NameError: ignored

### Cual es la diferencia entre un array de numpy y un series de Pandas

El array de NumPy tiene un índice entero definido implícitamente que se utiliza para acceder a los valores y Series de Pandas tiene un índice definido explícitamente asociado a los valores. Mientras que, hasta ahora, Series de Pandas siempre han empezado en 0, pueden tener índices que pueden ser cadenas e incluso si tienen valores números, no tienen que empezar en 0. El 0 es simplemente el valor por defecto. En el código de abajo, el índice para un Series de Pandas resulta ser las fechas.