Un bucle for se usa para iterar una secuencia (lista, tupla, diccionario, cadena, etc).

 En la primera iteración del bucle de abajo, será igual al elemento siguiente en la lista. 
 
 
Por lo que la primera vez a través del bucle, x será igual a M. La próxima vez, x será igual a i, y así sucesivamente hasta que llegue al final de la cadena.

In [2]:
myName = "FELIPE"
for x in myName:
    print(x)

F
E
L
I
P
E

In [3]:
dataScienceTools = ['Python', 'R', 'SQL', 'Git']
for i in range(len(dataScienceTools)):
    print(dataScienceTools[i])

Python
R
SQL
Git

In [4]:
dataScienceTools = ['Python', 'R', 'SQL', 'Git']
for index, tool in enumerate(dataScienceTools):
    print(index,tool)

0 Python
1 R
2 SQL
3 Git